import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';
import { jsPDF } from 'npm:jspdf@2.5.2';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }
    
    const { prescription } = await req.json();
    
    if (!prescription) {
      return Response.json({ error: 'Missing prescription data' }, { status: 400 });
    }
    
    // Create PDF
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(241, 245, 249);
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('AUTRYST AI Healthcare', 20, 20);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text('Digitally Generated Medical Prescription', 20, 28);
    
    // Patient Info
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105);
    doc.text(`Patient: ${prescription.patient_name}`, 140, 20);
    doc.text(`Date: ${prescription.date}`, 140, 27);
    
    let yPos = 50;
    
    // Diagnosis
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(51, 65, 85);
    doc.text('Diagnosis', 20, yPos);
    
    yPos += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    const diagnosisLines = doc.splitTextToSize(prescription.diagnosis || 'Not specified', 170);
    doc.text(diagnosisLines, 20, yPos);
    yPos += diagnosisLines.length * 6 + 10;
    
    // Medications
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(51, 65, 85);
    doc.text('Medications', 20, yPos);
    yPos += 10;
    
    if (prescription.medications && prescription.medications.length > 0) {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      
      prescription.medications.forEach((med, index) => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }
        
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(20, yPos - 5, 170, 20, 3, 3, 'F');
        
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(30, 41, 59);
        doc.text(`${index + 1}. ${med.name}`, 25, yPos);
        
        yPos += 6;
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(71, 85, 105);
        doc.text(`${med.dosage} - ${med.frequency}`, 25, yPos);
        
        if (med.instructions) {
          yPos += 5;
          doc.setFontSize(9);
          doc.setTextColor(100, 116, 139);
          const instrLines = doc.splitTextToSize(med.instructions, 160);
          doc.text(instrLines, 25, yPos);
          yPos += instrLines.length * 4;
        }
        
        yPos += 10;
        doc.setFontSize(10);
      });
    } else {
      doc.setTextColor(148, 163, 184);
      doc.text('No medications prescribed.', 20, yPos);
      yPos += 10;
    }
    
    // Care Instructions
    if (yPos > 230) {
      doc.addPage();
      yPos = 20;
    }
    
    yPos += 5;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(51, 65, 85);
    doc.text('Care Instructions', 20, yPos);
    
    yPos += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    const careLines = doc.splitTextToSize(prescription.care_instructions || 'Not specified', 170);
    doc.text(careLines, 20, yPos);
    yPos += careLines.length * 6 + 10;
    
    // Follow-up
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(51, 65, 85);
    doc.text('Follow-up', 20, yPos);
    
    yPos += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    const followUpLines = doc.splitTextToSize(prescription.follow_up || 'Not specified', 170);
    doc.text(followUpLines, 20, yPos);
    
    // Footer
    const pageCount = doc.internal.pages.length - 1;
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Generated by AUTRYST AI Healthcare System`, 20, 285);
      doc.text(`Page ${i} of ${pageCount}`, 180, 285);
    }
    
    // Convert to base64
    const pdfBase64 = doc.output('datauristring').split(',')[1];
    
    return Response.json({ 
      pdf: pdfBase64,
      filename: `prescription_${prescription.patient_name?.replace(/\s+/g, '_')}_${prescription.date}.pdf`
    });
    
  } catch (error) {
    console.error('Error generating PDF:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});